jms_translation:
    configs:
        admin_modules:
            dirs:
                - '%kernel.project_dir%/vendor/ezsystems/ezplatform-admin-ui-modules/src'
            output_dir: '%kernel.project_dir%/vendor/ezsystems/ezplatform-admin-ui-modules/Resources/translations/'
            excluded_dirs: [Behat, Tests, node_modules]
            output_format: "xliff"
