version: '2'
# compose file for installing composer packages using same php image as the others

services:
  install:
    image: ezsystems/php:${PHP_VERSION}-v0
    volumes:
     - ${COMPOSE_DIR}/../..:/var/www
     - $COMPOSER_HOME:/home/ez/.composer
    environment:
     - SYMFONY_ENV
     - SYMFONY_DEBUG
    # Dumping autoload using --optimize-autoloader to keep performenace on a usable level, not needed on linux host.
    command: /bin/sh -c "composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader"
