# This file describes an application. You can have multiple applications
# in the same project.

# Please see doc/platformsh/README.md and doc/platformsh/INSTALL.md

# Vocabulary:
# - PE: Platform.sh Enterprise
# - PS: Platform.sh Professional

# The name of this app. Must be unique within a project.
name: ez

# The type of the application to build.
type: php:7.2
build:
    # "none" means we're running composer manually, see build hook
    flavor: "none"

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'mysqldb:user'
    # Uncomment if you want to store dfs tables in a separate database:
    #dfs_database: 'mysqldb:dfs'
    rediscache: 'rediscache:redis'
    # If you wish to have a separate Redis instance for sessions, uncomment
    # this relationship and the corresponding service in .platform/services.yaml
    #redissession: 'redissession:redis'
    # If you wish to use solr, uncomment this relationship and the corresponding service in .platform/services.yaml
    #solr: 'solrsearch:solr'

variables:
    #php:
        # Example of setting php.ini config
        #"display_errors": "On"
    env:
        # For PE cluster, disable Symfony Proxy & instead use Fastly Bundle available on eZ Platform Enterprise
        #SYMFONY_HTTP_CACHE: 0
        # Place symfony cache on tmpfs to avoid performance issues of having it on NFS, re-deploy to clear cache reliably
        # "ez" comes from application name for platform.sh, so adapt it if you change the name for multi application setups
        SYMFONY_CACHE_DIR: /tmp/ez
        # PS: Given we just set cache directory to be non shared, we need to make sure http cache is shared (ignored when using Fastly)
        SYMFONY_HTTP_CACHE_DIR: app/cache/prod
        # Change this to dev if you want to run site & commands in dev
        SYMFONY_ENV: prod
        # Uncomment if you want to use DFS clustering:
        #PLATFORMSH_DFS_NFS_PATH: 'dfsdata'

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/app.php"
            # The number of seconds whitelisted (static) content should be cache
            expires: 600

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/app/logs": "shared:files/logs"
    "/web/var": "shared:files/files"
    # Uncomment if you want to use DFS clustering:
    #"/dfsdata": "shared:files/dfsdata"

# The hooks that will be performed when the package is deployed.
hooks:
    # Build hook, done once before connected to services, disk is still writable here
    build: |
        set -e
        rm web/app_dev.php
        if [ "$SYMFONY_ENV" = "dev" ] ; then
            composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
        else
            composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader
        fi
    # Deploy hook, access to services & done once (per cluster, not per node), only mounts & tmpfs are writable at this point
    # Note: Http traffic is paused while this is running, so for prod code this should finish as fast as possible, < 30s
    deploy: |
        set -e
        # Mainly relevant for eZ Platform demo usage, for own setup adapt this, or remove and rely on migrations.
        if [ ! -f web/var/.platform.installed ]; then
            . ./.env
            php -d memory_limit=-1 app/console ezplatform:install $INSTALL_EZ_INSTALL_TYPE
            touch web/var/.platform.installed
        fi
        # Clear class/lazy-proxy cache before we boot up symfony in case of interface changes on classes cached
        rm -Rf $SYMFONY_CACHE_DIR/app/cache/$SYMFONY_ENV/*.*
        # Clear cache, but leave warmup to be done on-demand and per node at startup (web.commands.start)
        app/console cache:clear --no-warmup
        # Example of additional deploy hooks if you use doctrine and/or kaliop migration bundle
        ##app/console doctrine:migrations:migrate --no-interaction --allow-no-migration
        ##app/console kaliop:migration:migrate --no-interaction --no-debug
        # If migration changes happened and they did not use API, then: clear redis cache & exire Http cache

# Given we place cache per node we opt to warmup cache before letting requests hit them, NOTE:
# 1. Adapt this if you change php version*, 2. For PE setups, open support ticket to platform.sh for adapting changes
# * https://docs.platform.sh/languages/php.html#alternate-start-commands
web:
    commands:
        start: 'app/console cache:warmup && /usr/sbin/php-fpm7.2-zts'


# The configuration of scheduled execution.
# see http://symfony.com/doc/current/components/console/introduction.html
#crons:
#    symfony:
#        spec: "*/20 * * * *"
#        cmd: "php app/console ezpublish:cron:run"

runtime:
    extensions:
        - xsl
        - imagick
        - readline
        - redis
        #- apcu
        #- name: 'blackfire'
        #  configuration:
        #      server_id: 'xxxx-xxx-xxx-xxx-xxxx'
        #      server_token: 'xxxx'

