imports:
    - { resource: config.yml }
    - { resource: ezplatform_prod.yml }

# If you are on Platform.sh/docker or similar where app/cache is not writable during runtime
# Enabling apc(u)/redis caching might be the answer.

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
## Result (& the experimental Second level) cache needs to be shared among servers so should use for instance Redis
#        result_cache_driver:
#            type: redis
#            host:
#            port:


monolog:
    handlers:
        main:
            type: fingers_crossed
            # eZ Platform sets this to critical instead of error to avoid too verbose logs in prod
            action_level: critical
            handler: nested
        nested:
            type: '%log_type%'
            path: '%log_path%'
            level: debug
        console:
            type: console
