imports:
    - { resource: config.yml }
    - { resource: ezplatform_prod.yml }

# Example below would make sure some of the symfony caches are written to apc / redis instead of disk
# Make sure to verify if cache clearing is done as you expect when doing such changes.

#framework:
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.apc
#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        query_cache_driver: apc
## Result (& the experimental Second level) cache needs to be shared among servers so should use for instance Redis
#        result_cache_driver:
#            type: redis
#            host:
#            port:


monolog:
    handlers:
        main:
            type: fingers_crossed
            # eZ Platform sets this to critical instead of error to avoid too verbose logs in prod
            action_level: critical
            handler: nested
        nested:
            type: '%log_type%'
            path: '%log_path%'
            level: debug
        console:
            type: console
            process_psr_3_messages: false
