# This custom cache pool "singleredis" is loaded by generic.php and plaformsh.php on demand
stash:
    caches:
        singleredis:
            drivers: [Redis]
            Redis:
                servers: [ {server: '%cache_host%', port: '%cache_redis_port%'} ]
