# Only settings different then parameters.yml.dist, buildParameters will inject those we don't define from there!
parameters:
    env(DATABASE_NAME): behattestdb
    env(DATABASE_USER): ezp
    env(DATABASE_PASSWORD): ezp
