services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    # @todo Move this to BehatBundle
    EzSystems\Behat\API\Context\:
        resource: '../vendor/ezsystems/behatbundle/src/lib/API/Context/*'
        public: true

    eZ\Bundle\EzPublishCoreBundle\Features\Context\:
        resource: '../vendor/ezsystems/ezpublish-kernel/eZ/Bundle/EzPublishCoreBundle/Features/Context//*'
        public: true

    # @todo This could be loaded via ezpublish-kernel based on current env
    eZ\Bundle\EzPublishCoreBundle\Features\Context\ContentContext:
        public: true
        arguments:
            $repository: '@ezpublish.api.repository'

    eZ\Bundle\EzPublishCoreBundle\Features\Context\ConsoleContext:
        public: true
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $siteaccessList: '%ezpublish.siteaccess.list%'
            $defaultSiteaccess: '%ezpublish.siteaccess.default%'

    eZ\Bundle\EzPublishCoreBundle\Features\Context\YamlConfigurationContext:
        public: true
        arguments:
            $kernel: '@kernel'

    eZ\Bundle\EzPublishCoreBundle\Features\Context\QueryControllerContext:
        public: true
        arguments:
            $repository: '@ezpublish.api.repository'

    eZ\Bundle\EzPublishCoreBundle\Features\Context\ContentTypeContext:
        public: true
        arguments:
            $contentTypeService: '@ezpublish.api.service.content_type'

    EzSystems\Behat\API\Context\TestContext:
        public: true
        arguments:
            $userService: '@ezpublish.api.service.user'
            $permissionResolver: '@=service("ezpublish.api.repository").getPermissionResolver()'

    EzSystems\Behat\Core\Context\ConfigurationContext:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'


    EzSystems\Behat\Core\Context\FileContext:
        public: true
        arguments:
            $projectDirectory: '%kernel.project_dir%'
