version: '2'
# Dev config, mounts from host directory, depends on prod.yml

services:
  app:
    build: {}
    image: ${PHP_IMAGE}
    volumes:
     - ${COMPOSE_DIR}/../../:/var/www
     - ${COMPOSER_HOME}:/root/.composer
    depends_on:
     - db
    environment:
     - SYMFONY_ENV
     - SYMFONY_DEBUG
     - DATABASE_USER
     - DATABASE_PASSWORD
     - DATABASE_NAME
     - DATABASE_HOST=db
     # As write performance on shared folders and nfs is slow, put cache and log in shm for better perf on mac/win
     # However not optimal as for instance PhpStorm Symfony extensions relies on parsing cache files for auto completion
     - KERNEL_CACHE_DIR=/dev/shm/app/cache
     - KERNEL_LOGS_DIR=/dev/shm/app/logs
     # SHM is limited in size (typically 64mb), so we need to place profiles somwhere else
     - PROFILE_DSN=file:/tmp/symfony/profiler
