FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive

# Use packages from Varnish to get Varnsih 5.1 which is a bit more stable then Varnsih 5.0.0 in stretch
RUN apt-get install -q -y --force-yes --no-install-recommends ca-certificates curl \
    curl -s https://packagecloud.io/install/repositories/varnishcache/varnish5/script.deb.sh | bash

# If we need varnish modules this is one way, or we need to find a way to install on the package above.
#RUN \
#    apt-get update -q -y && \
#    apt-get install -q -y --force-yes --no-install-recommends ca-certificates varnish-modules varnish


EXPOSE 80 6082

CMD ["varnishd", "-F", "-a", ":80", "-T", ":6082", "-f", "/etc/varnish/default.vcl", "-s", "malloc,256M"]
