version: '3.3'

services:
  app:
    volumes:
     - vardir:/var/www/web/var
    depends_on:
     - dataset-vardir

  web:
    volumes:
     - vardir:/var/www/web/var:ro

  dataset-vardir:
    volumes:
     - vardir:/var/www/web/var:ro
    networks:
     - backend

  dataset-dbdump:
    volumes:
     - dbdump:/dbdump:ro
    networks:
     - backend

volumes:
  vardir:
