version: '3.3'

services:
  app:
    volumes:
     - vardir:/var/www/web/var
    depends_on:
     - demo-vardir

  web:
    volumes:
     - vardir:/var/www/web/var:ro

  demo-vardir:
    build:
      context: ../../
      dockerfile: doc/docker/Dockerfile-demo-vardir
    volumes:
     - vardir:/var/www/web/var:ro
    networks:
     - backend

volumes:
  vardir:
